version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - tempo
    volumes:
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources  # Mount the provisioning directory

  tempo:
    image: grafana/tempo:latest
    ports:
      - "9411:9411"      # Zipkin-compatible endpoint. Zipkin clients can send traces to this endpoint.
      - "3200:3200"      # Tempo query endpoint for Grafana. Grafana uses this endpoint to query Tempo for traces.
    volumes:
      - ./tempo-data:/var/lib/tempo
      - ./tempo.yaml:/etc/tempo/tempo.yaml
    environment:
      - TEMPO_STORAGE_BACKEND=local
    command: [ "-config.file=/etc/tempo/tempo.yaml" ]

  tempo-query:
    image: grafana/tempo-query:latest
    ports:
      - "16686:16686"   # Jaeger-compatible endpoint
    environment:
      - TEMPO_ADDRESS=tempo:3200
    depends_on:
      - tempo

volumes:
  tempo-data: