apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-index-html
data:
  index.html: |
    {{ .Values.indexHtml | default "<!doctype html><html><body>Default HTML content</body></html>" | nindent 4 }}