apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: postgresql
      version: '17.2.0'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: default
      interval: 1m
  values:
    auth:
      postgresql-username: "myuser"
      postgresql-password: "mypass"
      postgresql-database: "mydatabase"

