---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system # part of the flux cd configuration
spec:
  interval: 5m0s # how frequent the reconciliation is
  path: ./kustomize
  prune: true # use garbage collection to remove resources that are no longer in the repo
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: default
  timeout: 3m0s
  wait: true
