apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
spec:
  interval: 1m # how often flux cd should check for updates in the helm release file
  chart:
    spec:
      chart: ./charts/nginx
      sourceRef:
        kind: GitRepository
        name: flux-system # this repo was defined for flux cd at bootstrapping
        namespace: flux-system
      interval: 1m # how often flux cd should check for updates in the helm chart file
