apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: mysql # name of the HelmRepository resource
  namespace: default
spec:
  type: oci
  interval: 1m0s
  url: oci://registry-1.docker.io/bitnamicharts