# This repo is set up using docker/chartmuseum.
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: local-http-repo
  namespace: default
spec:
  interval: 1m0s
  url: http://192.168.0.11:8080
  secretRef:
    name: local-http-repo-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: local-http-repo-secret
  namespace: default
stringData:
  username: "chartuser"
  password: "mypass"