apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system # part of the flux cd configuration
spec:
  interval: 5m0s # how frequent the reconciliation is
  path: ./kustomize
  prune: true # use garbage collection to remove resources that are no longer in the repo
  sourceRef:
    kind: GitRepository
    name: podinfo # the name of the GitRepository resource, defined in podinfo-repo.yaml
  targetNamespace: default